### ISSUE TITLE
Bad Links in Transform Tool-Installation Page

### ISSUE THREAD

**Issue by radiosci** [NASA-PDS/transform#31]
## 🐛 Describe the bug
Link to GitHub under "Unpacking the Package" at https://nasa-pds.github.io/transform/install/index.html yields a 404 error.  That is, I can't download the Transform package following the instructions on the Transform Tool-Installation page.  Links to the two options under Download in the left menu bard don't work either (but they just give text "not found" messages.

## 📜 To Reproduce
1. Go to https://nasa-pds.github.io/transform/install/index.html
2. In the first sentence under Unpacking the Package, click on "Github".
3. Marvel at the cute graphics and digest the "404" error message
4. Return to the Installation page
5. Try to download the two types of delivery packages from the left menu bar; neither works  

  🕵️Expected behavior
I was expecting to find download buttons for a couple delivery options for the Transform Tool before the first error; I was expecting to download one or the other option from the left menu bar after that error.

## 📚 Version of Software Used
N/A

## 🩺 Test Data / Additional context
N/A

##  🏞Screenshots
<img width="1680" alt="Screen Shot 2022-05-20 at 11 01 34 AM" src="https://user-images.githubusercontent.com/65104309/169586814-79559973-de78-47a7-9e74-e9647273a7cc.png">

## 🖥 System Info
 -Mac OS 12.3
 - Safari 15.4 (17613.1.17.1.6)

---

**Comment by jordanpadams** [comment]
fixed per d58edf4406001c1e3b5fd22e902da07bba64316a
