### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/annotation/AnnotationReader

### ISSUE THREAD

**Issue by vegetablecatcat** [NASA-PDS/transform#51]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

i run this tool and then something goes wrong
![err](https://github.com/NASA-PDS/transform/assets/109726876/1f901a62-8073-4d04-be7e-cedba2eeaf4c)

### 🕵️ Expected behavior

I expected [...]

### 📜 To Reproduce

in command line, type "transform  myfile   - f csv ", then the error happens

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@vegetablecatcat can you send over the XML and associated product files you are trying to transform? A ZIP of them would be great

**Comment by jordanpadams** [comment]
@vegetablecatcat also, what version of Java do you have installed on your machine? Transform requires Java 11+.

**Comment by vegetablecatcat** [comment]
Dear Jordan Padams,


You can see the data i want to transform in the email attachment(cotaining a .lbl file , a .dat file and a .fmt file). And the data is a PDS3 version. I use JAVA 21&nbsp; to transform them.


Thank you very much for helping me.&nbsp;




1954304157
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NASA-PDS/transform"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月18日(星期六) 凌晨4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NASA-PDS/transform] Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/annotation/AnnotationReader (Issue #51)





 
@vegetablecatcat also, what version of Java do you have installed on your machine? Transform requires Java 11+.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

data.zip (50.31M, 2023年12月18日 09:49 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=08333137c36de99da8634d434361004e4d47040e0104020418050703074c0a0400001c0e5355034c0107520454580104560b045565693205544750191f08426108&code=5317ea2a

**Comment by vegetablecatcat** [comment]
@jordanpadams    except this TRANSFORM tool, do you hava any other way to open PDS data that i send to you few days ago?  I would be grateful if you could give me some advice.

**Comment by jordanpadams** [comment]
@vegetablecatcat the email attachment doesn’t work here. Can you actually upload it to GitHub?

another tool you can use to view PDS4 data is PDS viewer: https://sbnwiki.astro.umd.edu/wiki/PDS4_Viewer

**Comment by vegetablecatcat** [comment]
The email attachment : a zip file ,is too big to upload to here, you can see data i want to open with TRANSFORM tool in this link: https://pds-geosciences.wustl.edu/mro/mro-m-sharad-4-rdr-v1/mrosh_1001/data/rdr01xxx/rdr0168901/

**Comment by jordanpadams** [comment]
@vegetablecatcat I think this issue is due to a Java version error. Can you confirm the outputs of the following?

```
which version
```

```
echo $JAVA_HOME
```

You may have Java 21 installed, but it may not be appropriately added to your path, or JAVA_HOME is set to an older version of java.

**Comment by jordanpadams** [comment]
I put this information onto our discussion board to hopefully make this more clear in the future.
